In [1]:
import numpy as np

In [8]:
u1=np.array([3,1,0,1])
u2=np.array([1,2,1,1])
u3=np.array([-1,0,2,-1])
b=np.array([-3,-3,8,9])

In [33]:
A=np.array([u1,u2,u3]).T

In [36]:
AAt=np.dot(A.T,A)
Atb=np.dot(A.T,b)
sol=np.linalg.solve(AAt,Atb)
sol

array([-1.,  2.,  1.])

In [37]:
np.dot(A,sol)

array([-2.0000000e+00,  3.0000000e+00,  4.0000000e+00, -4.4408921e-16])

In [22]:
v1=u1
v2=u2-(((np.dot(u2,v1))/(np.dot(v1,v1))))*v1
v3=u3-(((np.dot(u3,v1))/(np.dot(v1,v1)))*v1)-(((np.dot(u3,v2))/(np.dot(v2,v2)))*v2)
v1=v1/np.linalg.norm(v1)
v2=v2/np.linalg.norm(v2)
v3=v3/np.linalg.norm(v3)
c1=np.dot(b,v1)
c2=np.dot(b,v2)
c3=np.dot(b,v3)

In [27]:
pw=c1*v1+c2*v2+c3*v3

In [28]:
pw

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00, -1.11022302e-16])